server:
  port: 8080
  ws:
    port: 8081

spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test"
  profiles:
    active: @profiles.active@
  main:
    banner-mode: OFF
    allow-bean-definition-overriding: true
  application:
    name: chat
  redis:
    host: xxx
    port: xxx
    password: xx
    lettuce:
      pool:
        max-active: 50
        max-idle: 8
        max-wait: -1ms
        min-idle: 3
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 25
      minimum-idle: 10
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource

minio:
  endpoint: http://127.0.0.1:9000
  outEndpoint: yrou minio endpoint
  access-key: yrou minio access-key
  secret-key: yrou minio secret-key
  bucket: yrou minio bucket

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false